### ISSUE TITLE
Oracle doesn't query for relationships properly

### ISSUE THREAD

**Issue by NullEntity** [jbogard/Respawn#52]
https://github.com/jbogard/Respawn/blob/6159862c315e1c92a6de732e6d2099ab237e35dd/Respawn/DbAdapter.cs#L515

This join should also be filtering on: AND a.r_owner=b.owner
If you have the same constraint in two different schemas the query will return a relationship between the tables on different schemas. Adding a test for this would probably be a good idea, but I'm not too sure on how to test it.

**Comment by jbogard** [comment]
PR?

**Comment by FranksDevRepo** [comment]
I provided a PR for this issue since we ran into the same problem NullEntity mentioned on our test servers.
A possible work around is to invoke respawn by the schema owner. If respawn is invoked by system user, or a user with privileges on another schema, sometimes we experienced foreign key constraint violations on our test pipelines after calling respawn. I could track down the issue to using named foreign key constraints with same names in different schemas.
Hope this helps.
